version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: testdb
    ports:
      - 3307:3306 # HOST:CONTAINER
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: admin
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    #   - C:/mysql/data:/var/lib/mysql